With DBConnection.NewCommand("AddInvoice", "AddInvoice", CommandType.StoredProcedure)
	.AddParameter("id", SqlDbType.int, ParameterDirection.InputOutput, 0, 0)
	.AddParameter("claim_id", SqlDbType.int, ParameterDirection.Input, 0, 0)
	.AddParameter("claim_type", SqlDbType.char, ParameterDirection.Input, 4, "")
	' .AddParameter("service_type", SqlDbType.char, ParameterDirection.Input, 3, "")
	.AddParameter("service_no", SqlDbType.varchar, ParameterDirection.InputOutput, 22, "")
	' .AddParameter("service_date", SqlDbType.datetime, ParameterDirection.Input, 0, Nothing)
	' .AddParameter("version_no", SqlDbType.tinyint, ParameterDirection.Input, 0, 0)
	.AddParameter("service_sub_type", SqlDbType.char, ParameterDirection.Input, 4, "")
	' .AddParameter("document_type", SqlDbType.varchar, ParameterDirection.Input, 10, "")
	.AddParameter("reference_no1", SqlDbType.varchar, ParameterDirection.Input, 20, "")
	' .AddParameter("link_gop_id", SqlDbType.int, ParameterDirection.Input, 0, 0)
	.AddParameter("start_date", SqlDbType.datetime, ParameterDirection.Input, 0, Nothing)
	.AddParameter("end_date", SqlDbType.datetime, ParameterDirection.Input, 0, Nothing)
	' .AddParameter("diagnosis_code", SqlDbType.varchar, ParameterDirection.Input, 10, "")
	' .AddParameter("diagnosis_notes", SqlDbType.text, ParameterDirection.Input, -1, "")
	' .AddParameter("final_diagnosis_code", SqlDbType.varchar, ParameterDirection.Input, 10, "")
	' .AddParameter("final_diagnosis_notes", SqlDbType.text, ParameterDirection.Input, -1, "")
	' .AddParameter("procedure_code", SqlDbType.varchar, ParameterDirection.Input, 10, "")
	' .AddParameter("procedure_notes", SqlDbType.text, ParameterDirection.Input, -1, "")
	.AddParameter("provider_id", SqlDbType.int, ParameterDirection.Input, 0, 0)
	' .AddParameter("provider_contact_person", SqlDbType.varchar, ParameterDirection.Input, 100, "")
	' .AddParameter("provider_fax_no", SqlDbType.varchar, ParameterDirection.Input, 20, "")
	.AddParameter("doctor_id", SqlDbType.int, ParameterDirection.Input, 0, 0)
	' .AddParameter("length_of_stay", SqlDbType.int, ParameterDirection.Input, 0, 0)
	.AddParameter("treatment_country_code", SqlDbType.char, ParameterDirection.Input, 3, "")
	.AddParameter("invoice_no", SqlDbType.varchar, ParameterDirection.Input, 15, "")
	.AddParameter("invoice_date", SqlDbType.datetime, ParameterDirection.Input, 0, Nothing)
	.AddParameter("invoice_received_date", SqlDbType.datetime, ParameterDirection.Input, 0, Nothing)
	.AddParameter("invoice_entry_date", SqlDbType.datetime, ParameterDirection.Input, 0, Nothing)
	.AddParameter("invoice_entry_user", SqlDbType.char, ParameterDirection.Input, 10, "")
	.AddParameter("discount_type", SqlDbType.char, ParameterDirection.Input, 1, "")
	.AddParameter("discount_percent", SqlDbType.smallmoney, ParameterDirection.Input, 0, 0)
	.AddParameter("discount_amount", SqlDbType.money, ParameterDirection.Input, 0, 0)
	.AddParameter("claim_currency_code", SqlDbType.char, ParameterDirection.Input, 3, "")
	.AddParameter("claim_currency_to_base", SqlDbType.float, ParameterDirection.Input, 0, 0)
	.AddParameter("claim_currency_to_client", SqlDbType.float, ParameterDirection.Input, 0, 0)
	.AddParameter("claim_currency_to_eligibility", SqlDbType.float, ParameterDirection.Input, 0, 0)
	.AddParameter("claim_currency_rate_date", SqlDbType.datetime, ParameterDirection.Input, 0, Nothing)
	.AddParameter("claim_currency_manual_rate", SqlDbType.bit, ParameterDirection.Input, 0, 0)
	' .AddParameter("actual_amount", SqlDbType.money, ParameterDirection.Input, 0, 0)
	' .AddParameter("approved_amount", SqlDbType.money, ParameterDirection.Input, 0, 0)
	' .AddParameter("paid_amount", SqlDbType.money, ParameterDirection.Input, 0, 0)
	' .AddParameter("settlement_currency_code", SqlDbType.char, ParameterDirection.Input, 3, "")
	' .AddParameter("settlement_currency_to_claim", SqlDbType.float, ParameterDirection.Input, 0, 0)
	' .AddParameter("settlement_currency_to_base", SqlDbType.float, ParameterDirection.Input, 0, 0)
	' .AddParameter("settlement_currency_to_client", SqlDbType.float, ParameterDirection.Input, 0, 0)
	' .AddParameter("settlement_currency_to_eligibility", SqlDbType.float, ParameterDirection.Input, 0, 0)
	' .AddParameter("settlement_currency_rate_date", SqlDbType.datetime, ParameterDirection.Input, 0, Nothing)
	' .AddParameter("settlement_currency_manual_rate", SqlDbType.bit, ParameterDirection.Input, 0, 0)
	.AddParameter("status_code", SqlDbType.char, ParameterDirection.Input, 1, "")
	.AddParameter("sub_status_code", SqlDbType.char, ParameterDirection.Input, 3, "")
	' .AddParameter("status_date", SqlDbType.datetime, ParameterDirection.Input, 0, Nothing)
	' .AddParameter("status_user", SqlDbType.varchar, ParameterDirection.Input, 10, "")
	.AddParameter("medical_type", SqlDbType.char, ParameterDirection.Input, 1, "")
	.AddParameter("delivery_type", SqlDbType.char, ParameterDirection.Input, 1, "")
	.AddParameter("room_type", SqlDbType.char, ParameterDirection.Input, 1, "")
	' .AddParameter("float_id", SqlDbType.int, ParameterDirection.Input, 0, 0)
	' .AddParameter("payment_id", SqlDbType.int, ParameterDirection.Input, 0, 0)
	' .AddParameter("payee_type", SqlDbType.char, ParameterDirection.Input, 1, "")
	' .AddParameter("payee_id", SqlDbType.int, ParameterDirection.Input, 0, 0)
	' .AddParameter("payee_name", SqlDbType.varchar, ParameterDirection.Input, 100, "")
	.AddParameter("payment_mode", SqlDbType.char, ParameterDirection.Input, 1, "")
	' .AddParameter("is_recovery", SqlDbType.tinyint, ParameterDirection.Input, 0, 0)
	' .AddParameter("is_exgratia", SqlDbType.bit, ParameterDirection.Input, 0, 0)
	' .AddParameter("is_emergency", SqlDbType.bit, ParameterDirection.Input, 0, 0)
	.AddParameter("is_accident", SqlDbType.bit, ParameterDirection.Input, 0, 0)
	' .AddParameter("is_surgical", SqlDbType.bit, ParameterDirection.Input, 0, 0)
	' .AddParameter("authorize_user", SqlDbType.varchar, ParameterDirection.Input, 10, "")
	' .AddParameter("authorize_date", SqlDbType.datetime, ParameterDirection.Input, 0, Nothing)
	' .AddParameter("batch_id", SqlDbType.int, ParameterDirection.Input, 0, 0)
	' .AddParameter("batch_user", SqlDbType.varchar, ParameterDirection.Input, 10, "")
	' .AddParameter("batch_date", SqlDbType.datetime, ParameterDirection.Input, 0, Nothing)
	' .AddParameter("settlement_advice_id", SqlDbType.int, ParameterDirection.Input, 0, 0)
	.AddParameter("settlement_advice_notes", SqlDbType.text, ParameterDirection.Input, -1, "")
	' .AddParameter("protection_level", SqlDbType.int, ParameterDirection.Input, 0, 0)
	' .AddParameter("is_deleted", SqlDbType.tinyint, ParameterDirection.Input, 0, 0)
	' .AddParameter("create_date", SqlDbType.datetime, ParameterDirection.Input, 0, Nothing)
	' .AddParameter("create_user", SqlDbType.varchar, ParameterDirection.Input, 10, "")
	' .AddParameter("update_date", SqlDbType.datetime, ParameterDirection.Input, 0, Nothing)
	' .AddParameter("update_user", SqlDbType.varchar, ParameterDirection.Input, 10, "")

	
	.AddParameter("action", SqlDbType.Int, ParameterDirection.Input, 0, 0)
	.AddParameter("visit_id", SqlDbType.bigint, ParameterDirection.Input, 0, 0)
	.AddParameter("action_status_id", SqlDbType.Int, ParameterDirection.InputOutput, 0, 0)
	.AddParameter("action_msg", SqlDbType.VarChar, ParameterDirection.InputOutput, 200, "")
End With

With DBConnection.NewCommand("GetInvoicePayment", "GetInvoicePayment", CommandType.StoredProcedure)
	.AddParameter("id", SqlDbType.int, ParameterDirection.Input, 0, 0)
	.AddParameter("visit_id", SqlDbType.bigint, ParameterDirection.Input, 0, 0)
End With