With DBConnection.NewCommand("GetMember", "GetMember", CommandType.StoredProcedure)
    .AddParameter("id", SqlDbType.int, ParameterDirection.Input, 0, 0)
    .AddParameter("visit_id", SqlDbType.bigint, ParameterDirection.Input, 0, 0)
End With 

With DBConnection.NewCommand("AddMember", "AddMember", CommandType.StoredProcedure)
	.AddParameter("id", SqlDbType.Int, ParameterDirection.InputOutput, 0, 0)
	.AddParameter("policy_id", SqlDbType.Int, ParameterDirection.Input, 0, 0)
	.AddParameter("plan_code", SqlDbType.VarChar, ParameterDirection.Input, 15, "")
	.AddParameter("name_id", SqlDbType.Int, ParameterDirection.InputOutput, 0, 0)
	.AddParameter("main_name_id", SqlDbType.Int, ParameterDirection.Input, 0, 0)
	.AddParameter("sequence_no", SqlDbType.SmallInt, ParameterDirection.Input, 0, 0)
	.AddParameter("certificate_no" , SqlDbType.VarChar, ParameterDirection.InputOutput, 25, 0)	
	.AddParameter("certificate_id", SqlDbType.Int, ParameterDirection.InputOutput, 0, 0)
	.AddParameter("dependent_code", SqlDbType.SmallInt, ParameterDirection.InputOutput, 0, 0)
	.AddParameter("relationship_code", SqlDbType.VarChar, ParameterDirection.Input, 2, "")
	.AddParameter("inception_date", SqlDbType.DateTime, ParameterDirection.Input, 0, Nothing)
	.AddParameter("start_date", SqlDbType.DateTime, ParameterDirection.Input, 0, Nothing)
	.AddParameter("end_date", SqlDbType.DateTime, ParameterDirection.Input, 0, Nothing)
	.AddParameter("cancelation_name", SqlDbType.DateTime, ParameterDirection.Input, 0, Nothing)
	.AddParameter("reinstatement_date", SqlDbType.DateTime, ParameterDirection.Input, 0, Nothing)
	.AddParameter("status_code" , SqlDbType.Char, ParameterDirection.Input, 1, "")
	.AddParameter("history_id", SqlDbType.Int, ParameterDirection.InputOutput, 0, 0)
	.AddParameter("reference_no1", SqlDbType.VarChar, ParameterDirection.Input, 25, "")
	.AddParameter("reference_no2", SqlDbType.VarChar, ParameterDirection.Input, 25, "")
	.AddParameter("reference_no3", SqlDbType.VarChar, ParameterDirection.Input, 25, "")	
	.AddParameter("notes", SqlDbType.varchar, ParameterDirection.Input, -1, "")
	.AddParameter("medical_history_notes", SqlDbType.varchar, ParameterDirection.Input, -1, "")
	.AddParameter("underwriting_notes", SqlDbType.varchar, ParameterDirection.Input, -1, "")	
	.AddParameter("first_name", SqlDbType.VarChar, ParameterDirection.Input, 30, "")
	.AddParameter("middle_name", SqlDbType.VarChar, ParameterDirection.Input, 30, "")
	.AddParameter("last_name", SqlDbType.VarChar, ParameterDirection.Input, 30, "")
	.AddParameter("gender", SqlDbType.VarChar, ParameterDirection.Input, 1, "")
	.AddParameter("dob", SqlDbType.DateTime, ParameterDirection.Input, 0, Nothing)
	.AddParameter("home_country_code", SqlDbType.VarChar, ParameterDirection.Input, 3, "")
	.AddParameter("nationality_code", SqlDbType.VarChar, ParameterDirection.Input, 10, "")
	.AddParameter("action", SqlDbType.Int, ParameterDirection.Input, 0, 0)
	.AddParameter("visit_id", SqlDbType.bigint, ParameterDirection.Input, 0, 0)
	.AddParameter("action_status_id", SqlDbType.Int, ParameterDirection.InputOutput, 0, 0)
	.AddParameter("action_msg", SqlDbType.VarChar, ParameterDirection.InputOutput, 200, "")
End With

With DBConnection.NewCommand("GetNewMemberInfo", "GetNewMemberInfo", CommandType.StoredProcedure)
	.AddParameter("plan_code", SqlDbType.VarChar, ParameterDirection.Input, 15, "")
	.AddParameter("member_id", SqlDbType.int, ParameterDirection.Input, 0, 0)
    .AddParameter("visit_id", SqlDbType.bigint, ParameterDirection.Input, 0, 0)
End With 

With DBConnection.NewCommand("GetMembersEnquiry", "GetMembersEnquiry", CommandType.StoredProcedure)
    ' .AddParameter("filter", SqlDbType.varchar, ParameterDirection.Input, 100, "")
    ' .AddParameter("client_id", SqlDbType.int, ParameterDirection.Input, 0, 0)
    ' .AddParameter("policy_no", SqlDbType.varchar, ParameterDirection.Input, 20, "")
    ' .AddParameter("certificate_id", SqlDbType.int, ParameterDirection.Input, 0, 0)
    .AddParameter("id", SqlDbType.int, ParameterDirection.Input, 0, 1)
    .AddParameter("visit_id", SqlDbType.bigint, ParameterDirection.Input, 0, 0)
    .AddParameter("page", SqlDbType.int, ParameterDirection.Input, 0, 1)
    .AddParameter("pagesize", SqlDbType.int, ParameterDirection.Input, 0, 0)
    .AddParameter("row_count", SqlDbType.int, ParameterDirection.InputOutput, 0, 0)
    .AddParameter("page_count", SqlDbType.int, ParameterDirection.InputOutput, 0, 0)
    .AddParameter("sort", SqlDbType.varchar, ParameterDirection.Input, 200, "")
    .AddParameter("order", SqlDbType.varchar, ParameterDirection.Input, 10, "")
End With 

With DBConnection.NewCommand("GetMemberMedicalNotes", "GetMemberMedicalNotes", CommandType.StoredProcedure)
    .AddParameter("id", SqlDbType.int, ParameterDirection.Input, 0, 1)
    .AddParameter("claim_id", SqlDbType.int, ParameterDirection.Input, 0, 1)
    .AddParameter("visit_id", SqlDbType.bigint, ParameterDirection.Input, 0, 0)
End With 

With DBConnection.NewCommand("GetMemberPlanHistory", "GetMemberPlanHistory", CommandType.StoredProcedure)
    .AddParameter("member_id", SqlDbType.int, ParameterDirection.Input, 0, 1)
    .AddParameter("visit_id", SqlDbType.bigint, ParameterDirection.Input, 0, 0)
End With 
